version: '3.3'
services:
  mov-detector-app:
    image: $APP_NAME
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /usr/lib/libvdostream.so.1:/usr/lib/libvdostream.so.1
      - /tmp:/output
      - /var/run/dbus:/var/run/dbus:rw


